"""
Curvature Estimation on Manifold Surfaces with Analytic Ground Truth
====================================================================
Benchmark on the torus (a smooth, closed manifold with no singularities)
to validate that all curvature estimators agree on well-behaved geometry.

Methods compared
----------------
1. **Ground truth** — K and H from the parametric fundamental forms.
2. **Blow-up** (ours) — level-1 iterated tangent blow-up.
3. **Jet fitting** (pre-computed, loaded from ``jet/`` folder).
4. **CNC** (pre-computed, loaded from ``cnc/`` folder).

Point-cloud files
-----------------
Generated by ``examples/io/sample_surfaces_to_txt.py``.  Format per line::

    x y z nx ny nz u v

Usage::

    python analytic_manifold.py
    python analytic_manifold.py --k-bu 25
    python analytic_manifold.py --no-polyscope       # plots only, no viewer
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

from tangent_blowups.geometry.iterated_grassmann import BlowUpLevel, extract_level1
from tangent_blowups.solvers.linalg import normalize_vectors


# =====================================================================
# Paths
# =====================================================================

def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _pointcloud_dir() -> Path:
    return _repo_root() / "data" / "sampled_surfaces"


# =====================================================================
# Loading
# =====================================================================

def _load_pointcloud():
    """Load (pts, normals, u, v) from the torus text file."""
    path = _pointcloud_dir() / "torus.txt"
    if not path.exists():
        raise FileNotFoundError(
            f"Point cloud not found: {path}\n"
            "Run  examples/io/sample_surfaces_to_txt.py  first."
        )
    data = np.loadtxt(path)
    pts = data[:, :3]
    nrm = data[:, 3:6]
    u = data[:, 6]
    v = data[:, 7]

    valid = (
        np.isfinite(pts).all(1)
        & np.isfinite(nrm).all(1)
        & (np.linalg.norm(nrm, axis=1) > 1e-8)
    )
    nrm = normalize_vectors(nrm)
    return pts[valid], nrm[valid], u[valid], v[valid]


# =====================================================================
# Analytic curvature for the torus
# =====================================================================

TORUS_R, TORUS_r = 2.0, 1.0


def torus_analytic(u, v, R=TORUS_R, r=TORUS_r):
    """Analytic Gaussian and mean curvature of the torus.

    K = cos(v) / (r * (R + r*cos(v)))
    H = (R + 2*r*cos(v)) / (2*r * (R + r*cos(v)))
    """
    u, v = np.asarray(u, float), np.asarray(v, float)
    cv = np.cos(v)
    denom = r * (R + r * cv)
    K = cv / denom
    H = (R + 2.0 * r * cv) / (2.0 * denom)
    H2 = H ** 2
    total = np.sqrt(np.maximum(4.0 * H2 - 2.0 * K, 0.0))
    return K, H2, total


# =====================================================================
# Curvature estimation wrappers
# =====================================================================

def _normals_to_frames(normals: np.ndarray) -> np.ndarray:
    """Build (N, 3, 2) tangent frames from normals."""
    N = len(normals)
    frames = np.empty((N, 3, 2))
    for i in range(N):
        n = normals[i]
        ref = np.array([1.0, 0.0, 0.0]) if abs(n[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
        t1 = np.cross(n, ref)
        t1 /= np.linalg.norm(t1) + 1e-30
        t2 = np.cross(n, t1)
        frames[i, :, 0] = t1
        frames[i, :, 1] = t2
    return frames


def _blowup_curvature(pts, normals, *, k=20, alpha=1.0, lam=0.0):
    """Returns dict with K, H2, total via level-1 blow-up."""
    frames = _normals_to_frames(normals)
    l0 = BlowUpLevel.from_point_tangents(pts, frames)
    l1 = l0.lift(k=k, alpha=alpha, lam=lam)
    inv = extract_level1(l1)
    K = inv.gaussian_curvature
    Tc = inv.total_curvature[:, 0]
    H2 = (Tc ** 2 + 2.0 * K) / 4.0
    return {"K": K, "H2": H2, "total": Tc}


def _load_jet_curvature(name: str) -> dict[str, np.ndarray] | None:
    """Load pre-computed jet-fitting curvatures from jet/ folder."""
    jet_path = Path(__file__).parent / "jet" / f"jet_{name}.txt"
    if not jet_path.exists():
        return None
    jet_data = np.loadtxt(jet_path)
    K = jet_data[:, 0]
    H = jet_data[:, 1]
    H2 = H**2
    total = np.sqrt(np.maximum(4.0 * H2 - 2.0 * K, 0.0))
    return {"K": K, "H2": H2, "total": total}


# =====================================================================
# Plotting helpers
# =====================================================================

QUANTITIES = ["K", "H2", "total"]
_QUANTITY_LABELS = {
    "K": r"$|K - K_{\mathrm{gt}}|$",
    "H2": r"$|H^2 - H^2_{\mathrm{gt}}|$",
    "total": r"$|\,\|h\| - \|h\|_{\mathrm{gt}}|$",
}
_QUANTITY_TITLES = {
    "K": r"Gaussian curvature $K$",
    "H2": r"Squared mean curvature $H^2$",
    "total": r"Total curvature $\|h\|$",
}
_METHOD_STYLE: dict[str, dict] = {
    "jet":     dict(color="#7f7f7f", marker="s", ls="--", lw=1.2),
    "cnc":     dict(color="#ff7f0e", marker="^", ls="-.", lw=1.2),
    "blow-up": dict(color="#1f77b4", marker="o", ls="-",  lw=1.6),
}
# Polyscope colormap names (lowercase)
CMAPS = {"K": "coolwarm", "H2": "viridis", "total": "inferno",
         "K_err": "reds", "H2_err": "reds", "total_err": "reds"}
# Matplotlib colormap names (case-sensitive)
MPL_CMAPS = {"K": "coolwarm", "H2": "viridis", "total": "inferno",
             "K_err": "Reds", "H2_err": "Reds", "total_err": "Reds"}
_POSITIVE_QUANTITIES = {"H2", "total", "H2_err", "total_err", "K_err"}
_QUANTITY_DISPLAY = {
    "K": r"Gaussian curvature $K$",
    "H2": r"$H^2$",
    "total": r"Curvature magnitude $\|h\|$",
}


def _clamp(vals, pct=5):
    finite = vals[np.isfinite(vals)]
    if len(finite) == 0:
        return np.nan_to_num(vals, nan=0.0), -1.0, 1.0
    lo, hi = np.percentile(finite, [pct, 100 - pct])
    vmax = max(abs(lo), abs(hi), 1e-15)
    clamped = np.clip(np.nan_to_num(vals, nan=0.0), -vmax, vmax)
    return clamped, -vmax, vmax


def _clamp_positive(vals, pct=5):
    finite = vals[np.isfinite(vals)]
    if len(finite) == 0:
        return np.nan_to_num(vals, nan=0.0), 0.0, 1.0
    hi = np.percentile(finite, 100 - pct)
    hi = max(hi, 1e-15)
    clamped = np.clip(np.nan_to_num(vals, nan=0.0), 0.0, hi)
    return clamped, 0.0, hi


# =====================================================================
# Error histogram plot (SGP figure)
# =====================================================================

def _plot_error_histograms(gt, methods, out_dir: Path):
    """Per-quantity error histograms comparing all methods."""
    plt.rcParams.update({
        "font.family": "serif",
        "font.size": 9,
        "axes.labelsize": 10,
        "axes.titlesize": 11,
        "legend.fontsize": 8.5,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "figure.dpi": 150,
    })

    estimation_methods = [m for m in methods if m != "ground truth"]
    n_q = len(QUANTITIES)
    fig, axes = plt.subplots(1, n_q, figsize=(3.25 * n_q, 2.6), sharey=False)

    for col, (ax, qname) in enumerate(zip(axes, QUANTITIES)):
        gt_vals = gt[qname]
        for mname in estimation_methods:
            est = methods[mname][qname]
            err = np.abs(est - gt_vals)
            mask = np.isfinite(err) & np.isfinite(gt_vals) & (err > 0)
            if mask.sum() < 10:
                continue
            sty = _METHOD_STYLE.get(mname, {})
            ax.hist(np.log10(err[mask]), bins=60, alpha=0.45,
                    color=sty.get("color"), label=mname, density=True)

        if col == n_q // 2:
            ax.set_xlabel(r"$\log_{10}$ |error|")
        else:
            ax.set_xlabel("")
        if col == 0:
            ax.set_ylabel("density")
        else:
            ax.set_ylabel("")
        ax.set_title(_QUANTITY_TITLES.get(qname, qname))
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.grid(True, which="major", alpha=0.25, lw=0.6)

    axes[-1].legend(frameon=True, fancybox=False, edgecolor="0.8",
                    loc="upper left")
    fig.tight_layout(w_pad=1.8)
    fname = out_dir / "torus_error_histograms.pdf"
    fig.savefig(fname, bbox_inches="tight")
    print(f"  Saved {fname}")
    plt.show()


# =====================================================================
# Error bar chart (SGP figure)
# =====================================================================

def _plot_error_bar_chart(gt, methods, out_dir: Path):
    """Grouped bar chart of median absolute error per method per quantity."""
    estimation_methods = [m for m in methods if m != "ground truth"]
    n_methods = len(estimation_methods)

    plt.rcParams.update({
        "font.family": "serif",
        "font.size": 9,
        "axes.labelsize": 10,
        "axes.titlesize": 11,
        "legend.fontsize": 8.5,
        "xtick.labelsize": 9,
        "ytick.labelsize": 8,
        "figure.dpi": 150,
    })

    x = np.arange(len(QUANTITIES))
    bar_width = 0.8 / n_methods

    fig, ax = plt.subplots(figsize=(5, 3.2))
    for j, mname in enumerate(estimation_methods):
        vals = []
        for qname in QUANTITIES:
            gt_v = gt[qname]
            est_v = methods[mname][qname]
            mask = np.isfinite(gt_v) & np.isfinite(est_v)
            mae = np.median(np.abs(gt_v[mask] - est_v[mask])) if mask.sum() > 3 else 0.0
            vals.append(mae)
        sty = _METHOD_STYLE.get(mname, {})
        ax.bar(x + j * bar_width, vals, bar_width, label=mname,
               color=sty.get("color"))

    quantity_labels = [r"$K$", r"$H^2$", r"$\|h\|$"]
    ax.set_xticks(x + bar_width * (n_methods - 1) / 2)
    ax.set_xticklabels(quantity_labels)
    ax.set_ylabel("median |error|")
    ax.set_title("Torus — curvature estimation error (manifold)")
    ax.legend(frameon=True, fancybox=False, edgecolor="0.8")
    ax.set_yscale("log")
    ax.grid(True, axis="y", alpha=0.3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    fig.tight_layout()
    fname = out_dir / "torus_error_bar_chart.pdf"
    fig.savefig(fname, bbox_inches="tight")
    print(f"  Saved {fname}")
    plt.show()


# =====================================================================
# Error vs v (poloidal angle) — shows spatial structure
# =====================================================================

def _plot_error_vs_v(v_param, gt, methods, out_dir: Path, n_bins=30):
    """Error as a function of poloidal angle v (curvature varies with v)."""
    plt.rcParams.update({
        "font.family": "serif",
        "font.size": 9,
        "axes.labelsize": 10,
        "axes.titlesize": 11,
        "legend.fontsize": 8.5,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "figure.dpi": 150,
    })

    estimation_methods = [m for m in methods if m != "ground truth"]
    n_q = len(QUANTITIES)
    fig, axes = plt.subplots(1, n_q, figsize=(3.25 * n_q, 2.6), sharey=False)

    for col, (ax, qname) in enumerate(zip(axes, QUANTITIES)):
        gt_vals = gt[qname]
        for mname in estimation_methods:
            est = methods[mname][qname]
            err = np.abs(est - gt_vals)
            mask = np.isfinite(err) & np.isfinite(v_param) & np.isfinite(gt_vals)
            vv, ee = v_param[mask], err[mask]
            if len(vv) < 10:
                continue

            bin_edges = np.linspace(0, 2 * np.pi, n_bins + 1)
            bin_centres = 0.5 * (bin_edges[:-1] + bin_edges[1:])
            bin_idx = np.clip(np.digitize(vv, bin_edges) - 1, 0, n_bins - 1)

            medians = np.array([
                np.median(ee[bin_idx == i]) if np.sum(bin_idx == i) > 0
                else np.nan for i in range(n_bins)
            ])
            q25 = np.array([
                np.percentile(ee[bin_idx == i], 25) if np.sum(bin_idx == i) > 2
                else np.nan for i in range(n_bins)
            ])
            q75 = np.array([
                np.percentile(ee[bin_idx == i], 75) if np.sum(bin_idx == i) > 2
                else np.nan for i in range(n_bins)
            ])

            sty = _METHOD_STYLE.get(mname, {})
            color = sty.get("color")
            ax.fill_between(bin_centres, q25, q75, alpha=0.12, color=color,
                            linewidth=0)
            ax.plot(bin_centres, medians, label=mname,
                    marker=sty.get("marker", "o"), markersize=3,
                    ls=sty.get("ls", "-"), lw=sty.get("lw", 1.2),
                    color=color)

        ax.set_xlabel(r"poloidal angle $v$")
        ax.set_ylabel(_QUANTITY_LABELS.get(qname, qname))
        ax.set_title(_QUANTITY_TITLES.get(qname, qname))
        ax.set_yscale("log")
        ax.set_xlim(0, 2 * np.pi)
        ax.set_xticks([0, np.pi / 2, np.pi, 3 * np.pi / 2, 2 * np.pi])
        ax.set_xticklabels(["0", r"$\pi/2$", r"$\pi$", r"$3\pi/2$", r"$2\pi$"])
        ax.yaxis.set_major_locator(ticker.LogLocator(numticks=6))
        ax.yaxis.set_minor_locator(ticker.LogLocator(
            subs=np.arange(2, 10) * 0.1, numticks=12))
        ax.yaxis.set_minor_formatter(ticker.NullFormatter())
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.grid(True, which="major", alpha=0.25, lw=0.6)

    axes[-1].legend(frameon=True, fancybox=False, edgecolor="0.8",
                    loc="upper right")
    fig.tight_layout(w_pad=1.8)
    fname = out_dir / "torus_error_vs_v.pdf"
    fig.savefig(fname, bbox_inches="tight")
    print(f"  Saved {fname}")
    plt.show()


# =====================================================================
# Curvature profile along poloidal angle (SGP figure)
# =====================================================================

_PROFILE_LABELS = {
    "K": r"$K$",
    "H2": r"$H^2$",
    "total": r"$\|h\|$",
}


def _plot_curvature_profile(v_param, gt, methods, out_dir: Path, n_bins=60):
    """Top row: curvature vs v with analytic curve.  Bottom row: |error|."""
    plt.rcParams.update({
        "font.family": "serif",
        "font.size": 8.5,
        "axes.labelsize": 9,
        "axes.titlesize": 10,
        "legend.fontsize": 7.5,
        "xtick.labelsize": 7.5,
        "ytick.labelsize": 7.5,
        "figure.dpi": 200,
    })

    estimation_methods = [m for m in methods if m != "ground truth"]
    n_q = len(QUANTITIES)
    fig, axes = plt.subplots(2, n_q, figsize=(2.8 * n_q, 4.4),
                             gridspec_kw={"height_ratios": [1.3, 1]})

    # Pre-compute analytic curves on a fine grid
    v_fine = np.linspace(0, 2 * np.pi, 500)
    gt_fine_K, gt_fine_H2, gt_fine_total = torus_analytic(
        np.zeros_like(v_fine), v_fine)
    gt_fine = {"K": gt_fine_K, "H2": gt_fine_H2, "total": gt_fine_total}

    # Bin edges and centres for the scatter data
    bin_edges = np.linspace(0, 2 * np.pi, n_bins + 1)
    bin_centres = 0.5 * (bin_edges[:-1] + bin_edges[1:])

    def _bin_stats(values, v_vals):
        mask = np.isfinite(values) & np.isfinite(v_vals)
        vv, ee = v_vals[mask], values[mask]
        idx = np.clip(np.digitize(vv, bin_edges) - 1, 0, n_bins - 1)
        med = np.full(n_bins, np.nan)
        q25 = np.full(n_bins, np.nan)
        q75 = np.full(n_bins, np.nan)
        for i in range(n_bins):
            sel = ee[idx == i]
            if len(sel) > 2:
                med[i] = np.median(sel)
                q25[i] = np.percentile(sel, 25)
                q75[i] = np.percentile(sel, 75)
        return med, q25, q75

    v_ticks = [0, np.pi / 2, np.pi, 3 * np.pi / 2, 2 * np.pi]
    v_tick_labels = ["0", r"$\pi/2$", r"$\pi$", r"$3\pi/2$", r"$2\pi$"]

    for col, qname in enumerate(QUANTITIES):
        ax_top = axes[0, col]
        ax_bot = axes[1, col]
        gt_vals = gt[qname]

        # --- Top row: curvature profile ---
        ax_top.plot(v_fine, gt_fine[qname], color="k", lw=1.4, ls="-",
                    label="analytic", zorder=10)

        for mname in estimation_methods:
            est = methods[mname][qname]
            sty = _METHOD_STYLE.get(mname, {})
            color = sty.get("color")
            med, q25, q75 = _bin_stats(est, v_param)
            ax_top.fill_between(bin_centres, q25, q75, alpha=0.15,
                                color=color, linewidth=0)
            ax_top.plot(bin_centres, med,
                        marker=sty.get("marker", "o"), markersize=2.5,
                        ls="none", color=color, label=mname, zorder=5)

        ax_top.set_title(_QUANTITY_TITLES.get(qname, qname))
        # y-label only on leftmost column
        if col == 0:
            ax_top.set_ylabel(_PROFILE_LABELS.get(qname, qname))
        else:
            ax_top.set_ylabel("")
        ax_top.set_xlim(0, 2 * np.pi)
        ax_top.set_xticks(v_ticks)
        ax_top.set_xticklabels([])
        ax_top.spines["top"].set_visible(False)
        ax_top.spines["right"].set_visible(False)
        ax_top.grid(True, alpha=0.2, lw=0.5)

        # --- Bottom row: absolute error ---
        for mname in estimation_methods:
            est = methods[mname][qname]
            err = np.abs(est - gt_vals)
            sty = _METHOD_STYLE.get(mname, {})
            color = sty.get("color")
            med, q25, q75 = _bin_stats(err, v_param)
            ax_bot.fill_between(bin_centres, q25, q75, alpha=0.12,
                                color=color, linewidth=0)
            ax_bot.plot(bin_centres, med,
                        marker=sty.get("marker", "o"), markersize=2.5,
                        ls=sty.get("ls", "-"), lw=sty.get("lw", 1.0),
                        color=color, label=mname)

        # x-label only on middle column
        if col == n_q // 2:
            ax_bot.set_xlabel(r"poloidal angle $v$")
        else:
            ax_bot.set_xlabel("")
        # y-label only on leftmost column
        if col == 0:
            ax_bot.set_ylabel("absolute error")
        else:
            ax_bot.set_ylabel("")
        ax_bot.set_yscale("log")
        ax_bot.set_xlim(0, 2 * np.pi)
        ax_bot.set_xticks(v_ticks)
        ax_bot.set_xticklabels(v_tick_labels)
        ax_bot.yaxis.set_major_locator(ticker.LogLocator(base=10, numticks=5))
        ax_bot.yaxis.set_minor_formatter(ticker.NullFormatter())
        ax_bot.spines["top"].set_visible(False)
        ax_bot.spines["right"].set_visible(False)
        ax_bot.grid(True, which="major", alpha=0.2, lw=0.5)

    # Single legend in top-right panel
    handles, labels = axes[0, -1].get_legend_handles_labels()
    axes[0, -1].legend(handles, labels, frameon=True, fancybox=False,
                       edgecolor="0.8", loc="upper right")

    fig.tight_layout(h_pad=0.4, w_pad=1.2)
    fname = out_dir / "torus_curvature_profile.pdf"
    fig.savefig(fname, bbox_inches="tight")
    print(f"  Saved {fname}")
    plt.show()


# =====================================================================
# Summary table (stdout)
# =====================================================================

def _print_summary_table(gt, methods):
    """Print a LaTeX-ready table of median absolute errors and correlations."""
    estimation_methods = [m for m in methods if m != "ground truth"]

    print("\n  %-10s" % "", end="")
    for qname in QUANTITIES:
        print(f"  {'MAE ' + qname:>12s}  {'corr ' + qname:>12s}", end="")
    print()

    for mname in estimation_methods:
        print(f"  {mname:10s}", end="")
        for qname in QUANTITIES:
            gt_v = gt[qname]
            est_v = methods[mname][qname]
            mask = np.isfinite(gt_v) & np.isfinite(est_v)
            if mask.sum() < 3:
                print(f"  {'---':>12s}  {'---':>12s}", end="")
                continue
            mae = np.median(np.abs(gt_v[mask] - est_v[mask]))
            r = np.corrcoef(gt_v[mask], est_v[mask])[0, 1]
            print(f"  {mae:12.6f}  {r:12.6f}", end="")
        print()

    # LaTeX table
    print("\n  % LaTeX table (paste into paper):")
    print(r"  \begin{tabular}{lccc}")
    print(r"    \toprule")
    print(r"    Method & $K$ & $H^2$ & $\|h\|$ \\")
    print(r"    \midrule")
    for mname in estimation_methods:
        row = f"    {mname}"
        for qname in QUANTITIES:
            gt_v = gt[qname]
            est_v = methods[mname][qname]
            mask = np.isfinite(gt_v) & np.isfinite(est_v)
            if mask.sum() < 3:
                row += " & ---"
                continue
            mae = np.median(np.abs(gt_v[mask] - est_v[mask]))
            row += f" & {mae:.2e}"
        row += r" \\"
        print(row)
    print(r"    \bottomrule")
    print(r"  \end{tabular}")


# =====================================================================
# Export helpers (PLY for Blender, colour bar PDF, data for external plots)
# =====================================================================

def _export_ply(pts, normals, panel_names, panel_data, state, ALL_QUANTITIES):
    """Export each method's coloured point cloud as a PLY file for Blender."""
    import matplotlib.pyplot as plt
    import matplotlib.colors as mcolors

    qname = ALL_QUANTITIES[state["quantity"]]
    normalize = state["normalize"]
    cmap = plt.get_cmap(MPL_CMAPS.get(qname, "viridis"))
    if qname.endswith("_err"):
        cmap = plt.get_cmap("viridis")

    for pname in panel_names:
        key = (qname, normalize)
        if key not in panel_data[pname]:
            continue
        vals, vmin, vmax = panel_data[pname][key]
        if state.get("vmin") is not None:
            vmin = state["vmin"]
        if state.get("vmax") is not None:
            vmax = state["vmax"]
        vals = np.clip(vals, vmin, vmax)
        norm = mcolors.Normalize(vmin=vmin, vmax=vmax)
        rgba = cmap(norm(vals))
        rgb = (rgba[:, :3] * 255).astype(np.uint8)

        N = len(pts)
        safe = pname.replace("/", "_").replace(" ", "_")
        fname = f"torus_{safe}_{qname}.ply"
        with open(fname, "w") as f:
            f.write("ply\n")
            f.write("format ascii 1.0\n")
            f.write(f"element vertex {N}\n")
            f.write("property float x\nproperty float y\nproperty float z\n")
            f.write("property float nx\nproperty float ny\nproperty float nz\n")
            f.write("property uchar red\nproperty uchar green\nproperty uchar blue\n")
            f.write("end_header\n")
            for i in range(N):
                f.write(f"{pts[i,0]} {pts[i,1]} {pts[i,2]} "
                        f"{normals[i,0]} {normals[i,1]} {normals[i,2]} "
                        f"{rgb[i,0]} {rgb[i,1]} {rgb[i,2]}\n")
        print(f"Saved {fname}")


def _export_colourbar(panel_names, panel_data, state, ALL_QUANTITIES):
    """Save a standalone colour bar PDF matching the current polyscope view."""
    import matplotlib.pyplot as plt
    import matplotlib.colors as mcolors

    qname = ALL_QUANTITIES[state["quantity"]]
    normalize = state["normalize"]
    key = (qname, normalize)
    vmin = vmax = None
    for name in panel_names:
        if key in panel_data[name]:
            _, vmin, vmax = panel_data[name][key]
            break
    if vmin is None:
        print("No data for current quantity.")
        return
    if state.get("vmin") is not None:
        vmin = state["vmin"]
    if state.get("vmax") is not None:
        vmax = state["vmax"]

    cmap = plt.get_cmap(MPL_CMAPS.get(qname, "viridis"))
    if qname.endswith("_err"):
        cmap = plt.get_cmap("viridis")
    norm = mcolors.Normalize(vmin=vmin, vmax=vmax)

    fig, ax = plt.subplots(figsize=(4.5, 0.35))
    cb = fig.colorbar(
        plt.cm.ScalarMappable(norm=norm, cmap=cmap),
        cax=ax, orientation="horizontal",
    )
    cb.set_label(_QUANTITY_DISPLAY.get(qname, qname))

    fname = f"colourbar_torus_{qname}.pdf"
    fig.savefig(fname, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved {fname}")


def _export_data(v_param, gt, methods):
    """Export all data needed to regenerate plots externally.

    Saves torus_curvature_data.npz with:
        v_param, gt_K, gt_H2, gt_total,
        <method>_K, <method>_H2, <method>_total for each estimation method,
        method_names.
    """
    estimation_methods = [m for m in methods if m != "ground truth"]
    data = {
        "v_param": v_param,
        "gt_K": gt["K"],
        "gt_H2": gt["H2"],
        "gt_total": gt["total"],
        "method_names": np.array(estimation_methods),
    }
    for mname in estimation_methods:
        safe = mname.replace("-", "_").replace(" ", "_")
        for qname in QUANTITIES:
            data[f"{safe}_{qname}"] = methods[mname][qname]

    fname = "torus_curvature_data.npz"
    np.savez(fname, **data)
    print(f"Saved {fname}")


# =====================================================================
# Polyscope viewer
# =====================================================================

def _show_polyscope(pts, normals, v_param, gt, methods):
    """Side-by-side panels: ground truth | jet | cnc | blow-up."""
    import polyscope as ps
    import polyscope.imgui as psim

    ps.init()
    ps.set_ground_plane_mode("shadow_only")

    method_names = list(methods.keys())
    bbox = pts.max(axis=0) - pts.min(axis=0)
    spacing = bbox[0] * 1.4

    ALL_QUANTITIES = QUANTITIES + [q + "_err" for q in QUANTITIES]

    # Compute error fields
    estimation_methods = [m for m in methods if m != "ground truth"]
    for mname in estimation_methods:
        for qname in QUANTITIES:
            methods[mname][qname + "_err"] = np.abs(
                methods[mname][qname] - gt[qname])
    for qname in QUANTITIES:
        gt[qname + "_err"] = np.zeros_like(gt[qname])

    # Shared colour ranges
    shared_range: dict[str, tuple[float, float]] = {}
    for qname in ALL_QUANTITIES:
        all_v = [methods[m][qname] for m in method_names if qname in methods[m]]
        if all_v:
            if qname in _POSITIVE_QUANTITIES:
                _, vmin, vmax = _clamp_positive(np.concatenate(all_v))
            else:
                _, vmin, vmax = _clamp(np.concatenate(all_v))
            shared_range[qname] = (vmin, vmax)
        else:
            shared_range[qname] = (-1.0, 1.0)

    panel_names: list[str] = []
    panel_data: dict[str, dict[tuple, tuple]] = {}
    for i, method in enumerate(method_names):
        offset = np.array([i * spacing, 0.0, 0.0])
        pname = f"torus/{method}"
        cloud = ps.register_point_cloud(pname, pts + offset, radius=0.001)
        cloud.set_color((0.75, 0.75, 0.75))
        panel_names.append(pname)
        panel_data[pname] = {}

        for qname in ALL_QUANTITIES:
            if qname not in methods[method]:
                continue
            raw = np.nan_to_num(methods[method][qname], nan=0.0)

            sv_min, sv_max = shared_range[qname]
            panel_data[pname][(qname, False)] = (
                np.clip(raw, sv_min, sv_max), sv_min, sv_max)

            if qname in _POSITIVE_QUANTITIES:
                _, pv_min, pv_max = _clamp_positive(methods[method][qname])
            else:
                _, pv_min, pv_max = _clamp(methods[method][qname])
            panel_data[pname][(qname, True)] = (
                np.clip(raw, pv_min, pv_max), pv_min, pv_max)

    # Initialise vmin/vmax from the first quantity's shared range
    _init_key = ("K", False)
    _init_vmin = _init_vmax = 0.0
    for _pn in panel_names:
        if _init_key in panel_data[_pn]:
            _, _init_vmin, _init_vmax = panel_data[_pn][_init_key]
            break

    state = {
        "quantity": 0, "normalize": False,
        "vmin": _init_vmin, "vmax": _init_vmax,
    }

    def _show_q(qname, normalize=False):
        key = (qname, normalize)
        cmap = CMAPS.get(qname, "viridis")
        if qname.endswith("_err"):
            cmap = CMAPS.get(qname, "Reds")
        vmin_o = state.get("vmin")
        vmax_o = state.get("vmax")
        for name in panel_names:
            if key in panel_data[name]:
                vals, vmin, vmax = panel_data[name][key]
                if vmin_o is not None:
                    vmin = vmin_o
                if vmax_o is not None:
                    vmax = vmax_o
                vals_clipped = np.clip(vals, vmin, vmax)
                ps.get_point_cloud(name).add_scalar_quantity(
                    "curvature", vals_clipped, enabled=True,
                    cmap=cmap, vminmax=(vmin, vmax))

    _show_q("K")

    def _refresh():
        _show_q(ALL_QUANTITIES[state["quantity"]], state["normalize"])

    def callback():
        psim.TextUnformatted(
            f"Torus (R={TORUS_R}, r={TORUS_r})  |  "
            f"Methods: {' | '.join(method_names)}")
        psim.Separator()

        changed_q, new_q = psim.Combo("Quantity", state["quantity"],
                                      ALL_QUANTITIES)
        if changed_q:
            state["quantity"] = new_q
            qname = ALL_QUANTITIES[new_q]
            key = (qname, state["normalize"])
            for _pn in panel_names:
                if key in panel_data[_pn]:
                    _, state["vmin"], state["vmax"] = panel_data[_pn][key]
                    break
            _refresh()

        changed_n, new_n = psim.Checkbox("Normalize per method",
                                         state["normalize"])
        if changed_n:
            state["normalize"] = new_n
            qname = ALL_QUANTITIES[state["quantity"]]
            key = (qname, new_n)
            for _pn in panel_names:
                if key in panel_data[_pn]:
                    _, state["vmin"], state["vmax"] = panel_data[_pn][key]
                    break
            _refresh()

        changed_vmin, new_vmin = psim.InputFloat("vmin", state["vmin"])
        changed_vmax, new_vmax = psim.InputFloat("vmax", state["vmax"])
        if changed_vmin or changed_vmax:
            state["vmin"] = new_vmin
            state["vmax"] = new_vmax
            _refresh()

        psim.Separator()
        if psim.Button("Export PLY"):
            _export_ply(pts, normals, panel_names, panel_data, state,
                        ALL_QUANTITIES)
        if psim.Button("Export colour bar"):
            _export_colourbar(panel_names, panel_data, state, ALL_QUANTITIES)
        if psim.Button("Export data (.npz)"):
            _export_data(v_param, gt, methods)
        if psim.Button("Screenshot"):
            fname = "torus_curvature.png"
            ps.screenshot(fname, transparent_bg=False)
            print(f"Saved {fname}")

    ps.set_user_callback(callback)
    ps.show()


# =====================================================================
# Main
# =====================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Manifold curvature benchmark on the torus"
    )
    parser.add_argument("--k-bu", type=int, default=20, help="k-NN for blow-up")
    parser.add_argument("--n-max", type=int, default=None,
                        help="Downsample to at most this many points")
    parser.add_argument("--no-polyscope", action="store_true",
                        help="Skip polyscope viewer, only generate plots")
    args = parser.parse_args()

    print("\n=== Torus (manifold benchmark) ===")
    pts, normals, u_p, v_p = _load_pointcloud()
    n_total = len(pts)

    if args.n_max is not None and n_total > args.n_max:
        rng = np.random.default_rng(42)
        idx = rng.choice(n_total, args.n_max, replace=False)
        pts, normals, u_p, v_p = pts[idx], normals[idx], u_p[idx], v_p[idx]
        print(f"  {len(pts)} points (downsampled from {n_total})")
    else:
        print(f"  {len(pts)} points")

    # Ground truth
    print("  Computing analytic curvature ...")
    K_gt, H2_gt, total_gt = torus_analytic(u_p, v_p)
    gt = {"K": K_gt, "H2": H2_gt, "total": total_gt}

    # Blow-up
    print("  Computing blow-up curvature ...")
    bu = _blowup_curvature(pts, normals, k=args.k_bu)

    # Build methods dict in display order
    methods: dict[str, dict[str, np.ndarray]] = {"ground truth": gt}

    # Jet fitting baseline (pre-computed, from jet/ folder)
    jf = _load_jet_curvature("torus")
    if jf is not None:
        print(f"  Loading jet-fitting curvatures from jet/ ...")
        methods["jet"] = jf

    # CNC baseline (if file exists)
    cnc_path = Path(__file__).parent / "cnc" / "cnc_torus.txt"
    if cnc_path.exists():
        print(f"  Loading CNC curvatures from {cnc_path} ...")
        cnc_data = np.loadtxt(cnc_path)
        K_cnc = cnc_data[:, 0]
        H_cnc = cnc_data[:, 1]
        H2_cnc = H_cnc ** 2
        total_cnc = np.sqrt(np.maximum(4.0 * H2_cnc - 2.0 * K_cnc, 0.0))
        methods["cnc"] = {"K": K_cnc, "H2": H2_cnc, "total": total_cnc}
    else:
        print(f"  CNC file not found ({cnc_path}), skipping CNC baseline.")
        print(f"  To add it, run CNC on data/sampled_surfaces/torus_xyzn.txt")

    methods["blow-up"] = bu

    # Print correlations
    estimation_methods = [m for m in methods if m != "ground truth"]
    for qname in QUANTITIES:
        gt_v = gt[qname]
        for mname in estimation_methods:
            est_v = methods[mname][qname]
            mask = np.isfinite(gt_v) & np.isfinite(est_v)
            if mask.sum() > 3:
                r = np.corrcoef(gt_v[mask], est_v[mask])[0, 1]
                rmse = np.sqrt(np.mean((gt_v[mask] - est_v[mask]) ** 2))
                print(f"    {qname:>5s} {mname:>8s}: corr={r:.4f}  RMSE={rmse:.6f}")

    _print_summary_table(gt, methods)

    # Generate plots
    out_dir = Path(__file__).parent
    _plot_error_bar_chart(gt, methods, out_dir)
    _plot_error_histograms(gt, methods, out_dir)
    _plot_error_vs_v(v_p, gt, methods, out_dir)
    _plot_curvature_profile(v_p, gt, methods, out_dir)

    # Polyscope
    if not args.no_polyscope:
        _show_polyscope(pts, normals, v_p, gt, methods)


if __name__ == "__main__":
    main()
