"""
Curvature Estimation on Parametric Surfaces with Analytic Ground Truth
======================================================================
Side-by-side comparison of curvature estimation methods on the Whitney
umbrella and Klein bottle, loaded from pre-sampled text files so that
every method is evaluated on the exact same point cloud.

Methods compared
----------------
1. **Ground truth** — K and H² from the parametric fundamental forms.
2. **Blow-up** (ours) — level-1 iterated tangent blow-up.
3. **Jet fitting** (pre-computed, loaded from ``jet/`` folder).
4. **CNC** (pre-computed, loaded from ``cnc/`` folder).

Point-cloud files
-----------------
Generated by ``examples/io/sample_surfaces_to_txt.py``.  Format per line::

    x y z nx ny nz u v

The ``u v`` columns are the parametric coordinates used for ground truth.

Usage::

    python analytic.py                       # both surfaces
    python analytic.py -s whitney            # Whitney umbrella only
    python analytic.py -s klein              # Klein bottle only
    python analytic.py --k-bu 25             # custom k-NN
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import polyscope as ps
import polyscope.imgui as psim

from tangent_blowups.geometry.iterated_grassmann import BlowUpLevel, extract_level1
from tangent_blowups.solvers.linalg import normalize_vectors


# =====================================================================
# Paths
# =====================================================================

def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _pointcloud_dir() -> Path:
    return _repo_root() / "data" / "sampled_surfaces"


# =====================================================================
# Loading
# =====================================================================

def _load_pointcloud(name: str):
    """Load (pts, normals, u, v) from the text file."""
    path = _pointcloud_dir() / f"{name}.txt"
    if not path.exists():
        raise FileNotFoundError(
            f"Point cloud not found: {path}\n"
            "Run  examples/io/sample_surfaces_to_txt.py  first."
        )
    data = np.loadtxt(path)
    pts = data[:, :3]
    nrm = data[:, 3:6]
    u = data[:, 6]
    v = data[:, 7]

    valid = (
        np.isfinite(pts).all(1)
        & np.isfinite(nrm).all(1)
        & (np.linalg.norm(nrm, axis=1) > 1e-8)
    )
    nrm = normalize_vectors(nrm)
    return pts[valid], nrm[valid], u[valid], v[valid]


# =====================================================================
# Analytic curvature formulae
# =====================================================================

def _fundamental_forms(dpdu, dpdv, dpuu, dpuv, dpvv):
    """(K, H) from parametric first/second fundamental forms."""
    E = np.sum(dpdu * dpdu, axis=-1)
    F = np.sum(dpdu * dpdv, axis=-1)
    G = np.sum(dpdv * dpdv, axis=-1)

    n_raw = np.cross(dpdu, dpdv)
    n_norm = np.linalg.norm(n_raw, axis=-1, keepdims=True)
    n_norm = np.where(n_norm > 1e-15, n_norm, 1.0)
    n_hat = n_raw / n_norm

    L = np.sum(dpuu * n_hat, axis=-1)
    M = np.sum(dpuv * n_hat, axis=-1)
    N_ = np.sum(dpvv * n_hat, axis=-1)

    det_I = E * G - F * F
    det_I = np.where(np.abs(det_I) > 1e-30, det_I, np.nan)

    K = (L * N_ - M * M) / det_I
    H = (E * N_ - 2.0 * F * M + G * L) / (2.0 * det_I)
    return K, H


def whitney_analytic(u, v, scale=1.0):
    s = scale
    u, v = np.asarray(u, float), np.asarray(v, float)
    dpdu = np.stack([s * v, np.full_like(u, s), np.zeros_like(u)], axis=-1)
    dpdv = np.stack([s * u, np.zeros_like(u), 2.0 * s * v], axis=-1)
    dpuu = np.zeros_like(dpdu)
    dpuv = np.stack([np.full_like(u, s), np.zeros_like(u),
                     np.zeros_like(u)], axis=-1)
    dpvv = np.stack([np.zeros_like(u), np.zeros_like(u),
                     np.full_like(u, 2.0 * s)], axis=-1)
    K, H = _fundamental_forms(dpdu, dpdv, dpuu, dpuv, dpvv)
    H2 = H ** 2
    total = np.sqrt(np.maximum(4.0 * H2 - 2.0 * K, 0.0))
    return K, H2, total


KLEIN_RADIUS, KLEIN_SCALE = 2.0, 1.0


def klein_analytic(u, v, radius=KLEIN_RADIUS, scale=KLEIN_SCALE):
    u, v = np.asarray(u, float), np.asarray(v, float)
    cu, su = np.cos(u), np.sin(u)
    cuh, suh = np.cos(0.5 * u), np.sin(0.5 * u)
    sv, cv = np.sin(v), np.cos(v)
    s2v, c2v = np.sin(2.0 * v), np.cos(2.0 * v)

    a = radius + cuh * sv - suh * s2v
    dadu = -0.5 * (suh * sv + cuh * s2v)
    dadv = cuh * cv - 2.0 * suh * c2v
    daduu = -0.25 * (cuh * sv - suh * s2v)
    daduv = -0.5 * (suh * cv + 2.0 * cuh * c2v)
    dadvv = -cuh * sv + 4.0 * suh * s2v

    dpdu = scale * np.stack([
        dadu * cu - a * su,
        dadu * su + a * cu,
        0.5 * (cuh * sv - suh * s2v),
    ], axis=-1)
    dpdv = scale * np.stack([
        dadv * cu, dadv * su,
        suh * cv + 2.0 * cuh * c2v,
    ], axis=-1)
    dpuu = scale * np.stack([
        daduu * cu - 2.0 * dadu * su - a * cu,
        daduu * su + 2.0 * dadu * cu - a * su,
        0.25 * (-suh * sv - cuh * s2v),
    ], axis=-1)
    dpuv = scale * np.stack([
        daduv * cu - dadv * su,
        daduv * su + dadv * cu,
        0.5 * (cuh * cv - 2.0 * suh * c2v),
    ], axis=-1)
    dpvv = scale * np.stack([
        dadvv * cu, dadvv * su,
        -suh * sv - 4.0 * cuh * s2v,
    ], axis=-1)

    K, H = _fundamental_forms(dpdu, dpdv, dpuu, dpuv, dpvv)
    H2 = H ** 2
    total = np.sqrt(np.maximum(4.0 * H2 - 2.0 * K, 0.0))
    return K, H2, total


# =====================================================================
# Singularity distance
# =====================================================================

def _whitney_singularity_distance(u, v, pts):
    """Distance from the pinch-point singularity line (u = 0)."""
    return np.abs(u)


def _klein_self_intersection_distance(u, v, pts, k=120):
    """Ambient distance to the nearest self-intersection point.

    For each point, find k spatial nearest neighbours and pick the
    closest one whose *parameter-space* distance (on the [0,2pi]^2
    torus) exceeds pi/2.  Small values flag points near the
    self-intersection curve.
    """
    from scipy.spatial import cKDTree

    tree = cKDTree(pts)
    dists, idx = tree.query(pts, k=k + 1)  # +1 because self is included
    # drop self
    dists, idx = dists[:, 1:], idx[:, 1:]

    # periodic parameter distance on [0, 2pi]^2
    du = np.abs(u[:, None] - u[idx])
    du = np.minimum(du, 2.0 * np.pi - du)
    dv = np.abs(v[:, None] - v[idx])
    dv = np.minimum(dv, 2.0 * np.pi - dv)
    param_dist = np.sqrt(du ** 2 + dv ** 2)

    # mask neighbours that are parametrically close (same sheet)
    far_in_param = param_dist > np.pi / 2.0
    dists_far = np.where(far_in_param, dists, np.inf)
    min_dist = dists_far.min(axis=1)
    return min_dist


# =====================================================================
# Curvature estimation wrappers
# =====================================================================

def _normals_to_frames(normals: np.ndarray) -> np.ndarray:
    """Build (N, 3, 2) tangent frames from normals."""
    N = len(normals)
    frames = np.empty((N, 3, 2))
    for i in range(N):
        n = normals[i]
        ref = np.array([1.0, 0.0, 0.0]) if abs(n[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
        t1 = np.cross(n, ref)
        t1 /= np.linalg.norm(t1) + 1e-30
        t2 = np.cross(n, t1)
        frames[i, :, 0] = t1
        frames[i, :, 1] = t2
    return frames


def _blowup_curvature(pts, normals, *, k=20, alpha=1.0, lam=0.0):
    """Returns dict with K, H2, total via level-1 blow-up."""
    frames = _normals_to_frames(normals)
    l0 = BlowUpLevel.from_point_tangents(pts, frames)
    l1 = l0.lift(k=k, alpha=alpha, lam=lam)
    inv = extract_level1(l1)
    K = inv.gaussian_curvature
    Tc = inv.total_curvature[:, 0]
    H2 = (Tc ** 2 + 2.0 * K) / 4.0
    return {"K": K, "H2": H2, "total": Tc}


def _load_jet_curvature(name: str) -> dict[str, np.ndarray] | None:
    """Load pre-computed jet-fitting curvatures from jet/ folder."""
    jet_path = Path(__file__).parent / "jet" / f"jet_{name}.txt"
    if not jet_path.exists():
        return None
    jet_data = np.loadtxt(jet_path)
    K = jet_data[:, 0]
    H = jet_data[:, 1]
    H2 = H**2
    total = np.sqrt(np.maximum(4.0 * H2 - 2.0 * K, 0.0))
    return {"K": K, "H2": H2, "total": total}


# =====================================================================
# Surface config
# =====================================================================

SURFACES = {
    "whitney_umbrella": dict(
        analytic=whitney_analytic,
        singularity_distance=_whitney_singularity_distance,
        singularity_label="|u|  (distance from pinch line)",
        singular_mask_fn=lambda u, v: np.abs(u) < 0.0001,
    ),
    "klein_bottle": dict(
        analytic=klein_analytic,
        singularity_distance=_klein_self_intersection_distance,
        singularity_label="ambient distance to self-intersection",
        singular_mask_fn=None,
    ),
}


# =====================================================================
# Polyscope helpers
# =====================================================================

QUANTITIES = ["K", "H2", "total"]
ERROR_QUANTITIES = ["K_err", "H2_err", "total_err"]
ALL_QUANTITIES = QUANTITIES + ERROR_QUANTITIES
# Polyscope colormap names (lowercase)
CMAPS = {"K": "coolwarm", "H2": "viridis", "total": "inferno",
         "K_err": "reds", "H2_err": "reds", "total_err": "reds"}
# Matplotlib colormap names (case-sensitive)
MPL_CMAPS = {"K": "coolwarm", "H2": "viridis", "total": "inferno",
             "K_err": "Reds", "H2_err": "Reds", "total_err": "Reds"}
_POSITIVE_QUANTITIES = {"H2", "total", "H2_err", "total_err", "K_err"}


def _clamp(vals, pct=5):
    finite = vals[np.isfinite(vals)]
    if len(finite) == 0:
        return np.nan_to_num(vals, nan=0.0), -1.0, 1.0
    lo, hi = np.percentile(finite, [pct, 100 - pct])
    vmax = max(abs(lo), abs(hi), 1e-15)
    clamped = np.clip(np.nan_to_num(vals, nan=0.0), -vmax, vmax)
    return clamped, -vmax, vmax


def _clamp_positive(vals, pct=5):
    finite = vals[np.isfinite(vals)]
    if len(finite) == 0:
        return np.nan_to_num(vals, nan=0.0), 0.0, 1.0
    hi = np.percentile(finite, 100 - pct)
    hi = max(hi, 1e-15)
    clamped = np.clip(np.nan_to_num(vals, nan=0.0), 0.0, hi)
    return clamped, 0.0, hi


def _show_quantity(qname, panel_names, panel_data, *, normalize=False,
                   vmin_override=None, vmax_override=None):
    key = (qname, normalize)
    cmap = CMAPS.get(qname, "viridis")
    for name in panel_names:
        if key in panel_data[name]:
            vals, vmin, vmax = panel_data[name][key]
            if vmin_override is not None:
                vmin = vmin_override
            if vmax_override is not None:
                vmax = vmax_override
            vals_clipped = np.clip(vals, vmin, vmax)
            ps.get_point_cloud(name).add_scalar_quantity(
                "curvature", vals_clipped, enabled=True,
                cmap=cmap, vminmax=(vmin, vmax),
            )


# =====================================================================
# Export helpers (PLY for Blender, colour bar PDF, data for external plots)
# =====================================================================

_QUANTITY_DISPLAY = {
    "K": r"Gaussian curvature $K$",
    "H2": r"$H^2$",
    "total": r"Curvature magnitude $\|h\|$",
}


def _export_ply(surface_name, pts, normals, panel_names, panel_data, state):
    """Export each method's coloured point cloud as a PLY file for Blender."""
    import matplotlib.pyplot as plt
    import matplotlib.colors as mcolors

    qname = ALL_QUANTITIES[state["quantity"]]
    normalize = state["normalize"]
    cmap = plt.get_cmap(MPL_CMAPS.get(qname, "viridis"))

    for pname in panel_names:
        key = (qname, normalize)
        if key not in panel_data[pname]:
            continue
        vals, vmin, vmax = panel_data[pname][key]
        if state.get("vmin") is not None:
            vmin = state["vmin"]
        if state.get("vmax") is not None:
            vmax = state["vmax"]
        vals = np.clip(vals, vmin, vmax)
        norm = mcolors.Normalize(vmin=vmin, vmax=vmax)
        rgba = cmap(norm(vals))
        rgb = (rgba[:, :3] * 255).astype(np.uint8)

        N = len(pts)
        safe = pname.replace("/", "_").replace(" ", "_")
        fname = f"{surface_name}_{safe}_{qname}.ply"
        with open(fname, "w") as f:
            f.write("ply\n")
            f.write("format ascii 1.0\n")
            f.write(f"element vertex {N}\n")
            f.write("property float x\nproperty float y\nproperty float z\n")
            f.write("property float nx\nproperty float ny\nproperty float nz\n")
            f.write("property uchar red\nproperty uchar green\nproperty uchar blue\n")
            f.write("end_header\n")
            for i in range(N):
                f.write(f"{pts[i,0]} {pts[i,1]} {pts[i,2]} "
                        f"{normals[i,0]} {normals[i,1]} {normals[i,2]} "
                        f"{rgb[i,0]} {rgb[i,1]} {rgb[i,2]}\n")
        print(f"Saved {fname}")


def _export_colourbar(surface_name, panel_names, panel_data, state):
    """Save a standalone colour bar PDF matching the current polyscope view."""
    import matplotlib.pyplot as plt
    import matplotlib.colors as mcolors

    qname = ALL_QUANTITIES[state["quantity"]]
    normalize = state["normalize"]
    key = (qname, normalize)
    vmin = vmax = None
    for name in panel_names:
        if key in panel_data[name]:
            _, vmin, vmax = panel_data[name][key]
            break
    if vmin is None:
        print("No data for current quantity.")
        return
    if state.get("vmin") is not None:
        vmin = state["vmin"]
    if state.get("vmax") is not None:
        vmax = state["vmax"]

    cmap = plt.get_cmap(MPL_CMAPS.get(qname, "viridis"))
    norm = mcolors.Normalize(vmin=vmin, vmax=vmax)

    fig, ax = plt.subplots(figsize=(4.5, 0.35))
    cb = fig.colorbar(
        plt.cm.ScalarMappable(norm=norm, cmap=cmap),
        cax=ax, orientation="horizontal",
    )
    cb.set_label(_QUANTITY_DISPLAY.get(qname, qname))

    fname = f"colourbar_{surface_name}_{qname}.pdf"
    fig.savefig(fname, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved {fname}")


def _export_data(results):
    """Export all data needed to regenerate plots externally.

    Saves one .npz per surface with:
        points, normals, sing_dist, u_params, v_params,
        gt_K, gt_H2, gt_total,
        <method>_K, <method>_H2, <method>_total  for each estimation method,
        method_names (list of method names excluding 'ground truth').
    """
    for res in results:
        sname = res["surface_name"]
        gt = res["gt"]
        methods = res["methods"]
        estimation_methods = [m for m in methods if m != "ground truth"]

        data = {
            "sing_dist": res["sing_dist"],
            "singularity_label": res["singularity_label"],
            "gt_K": gt["K"],
            "gt_H2": gt["H2"],
            "gt_total": gt["total"],
            "method_names": np.array(estimation_methods),
        }
        for mname in estimation_methods:
            safe = mname.replace("-", "_").replace(" ", "_")
            for qname in QUANTITIES:
                data[f"{safe}_{qname}"] = methods[mname][qname]

        fname = f"sing_dist_curvature_data_{sname}.npz"
        np.savez(fname, **data)
        print(f"Saved {fname}")


# =====================================================================
# Error vs distance from singularity (matplotlib)
# =====================================================================

_QUANTITY_LABELS = {"K": r"$|K - K_{\mathrm{gt}}|$",
                    "H2": r"$|H^2 - H^2_{\mathrm{gt}}|$",
                    "total": r"$|\,\|h\| - \|h\|_{\mathrm{gt}}|$"}
_QUANTITY_TITLES = {"K": r"Gaussian curvature $K$",
                    "H2": r"Squared mean curvature $H^2$",
                    "total": r"Total curvature $\|h\|$"}
_METHOD_STYLE: dict[str, dict] = {
    "jet":     dict(color="#7f7f7f", marker="s", ls="--", lw=1.2),
    "cnc":     dict(color="#ff7f0e", marker="^", ls="-.", lw=1.2),
    "blow-up": dict(color="#1f77b4", marker="o", ls="-",  lw=1.6),
}


def _plot_error_vs_distance(sing_dist, gt, methods, surface_name,
                            singularity_label, n_bins=25):
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker

    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
        "mathtext.fontset": "cm",
        "font.size": 9,
        "axes.labelsize": 10,
        "axes.titlesize": 11,
        "legend.fontsize": 8.5,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "figure.dpi": 150,
    })

    estimation_methods = [m for m in methods if m != "ground truth"]
    n_q = len(QUANTITIES)
    fig, axes = plt.subplots(1, n_q, figsize=(3.25 * n_q, 2.6), sharey=False)

    for col, (ax, qname) in enumerate(zip(axes, QUANTITIES)):
        gt_vals = gt[qname]
        for mname in estimation_methods:
            est = methods[mname][qname]
            err = np.abs(est - gt_vals)

            mask = np.isfinite(err) & np.isfinite(sing_dist) & np.isfinite(gt_vals)
            d, e = sing_dist[mask], err[mask]
            if len(d) < 10:
                continue

            bin_edges = np.linspace(d.min(), d.max(), n_bins + 1)
            bin_centres = 0.5 * (bin_edges[:-1] + bin_edges[1:])
            bin_idx = np.clip(np.digitize(d, bin_edges) - 1, 0, n_bins - 1)

            medians = np.array([
                np.median(e[bin_idx == i]) if np.sum(bin_idx == i) > 0
                else np.nan
                for i in range(n_bins)
            ])
            q25 = np.array([
                np.percentile(e[bin_idx == i], 25) if np.sum(bin_idx == i) > 2
                else np.nan
                for i in range(n_bins)
            ])
            q75 = np.array([
                np.percentile(e[bin_idx == i], 75) if np.sum(bin_idx == i) > 2
                else np.nan
                for i in range(n_bins)
            ])

            sty = _METHOD_STYLE.get(mname, {})
            color = sty.get("color", None)
            ax.fill_between(bin_centres, q25, q75, alpha=0.12, color=color,
                            linewidth=0)
            ax.plot(bin_centres, medians, label=mname,
                    marker=sty.get("marker", "o"), markersize=3,
                    ls=sty.get("ls", "-"), lw=sty.get("lw", 1.2),
                    color=color)

        # x-axis label only on the middle panel
        if col == n_q // 2:
            ax.set_xlabel(singularity_label)
        else:
            ax.set_xlabel("")

        # y-axis label only on the leftmost panel
        if col == 0:
            ax.set_ylabel("absolute error")
        else:
            ax.set_ylabel("")

        ax.set_title(_QUANTITY_TITLES.get(qname, qname))
        ax.set_yscale("log")
        # Fixed evenly-spaced log ticks
        ax.yaxis.set_major_locator(ticker.LogLocator(base=10, numticks=5))
        ax.yaxis.set_minor_formatter(ticker.NullFormatter())
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.grid(True, which="major", alpha=0.25, lw=0.6)

    axes[-1].legend(frameon=True, fancybox=False, edgecolor="0.8",
                    loc="upper right")

    fig.tight_layout(w_pad=1.8)
    fname = f"error_vs_singularity_{surface_name}.pdf"
    fig.savefig(fname, bbox_inches="tight")
    print(f"  Saved {fname}")
    plt.show()


def _plot_error_bar_chart(all_results):
    """Grouped bar chart: median absolute error per method per quantity per surface."""
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
        "mathtext.fontset": "cm",
        "font.size": 9,
        "axes.labelsize": 10,
        "axes.titlesize": 11,
        "legend.fontsize": 8.5,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "figure.dpi": 150,
    })

    # Collect (surface, method, quantity) -> median |error|
    rows = []
    for res in all_results:
        gt = res["gt"]
        estimation_methods = [m for m in res["methods"] if m != "ground truth"]
        for mname in estimation_methods:
            for qname in QUANTITIES:
                gt_v = gt[qname]
                est_v = res["methods"][mname][qname]
                mask = np.isfinite(gt_v) & np.isfinite(est_v)
                if mask.sum() < 3:
                    continue
                mae = np.median(np.abs(gt_v[mask] - est_v[mask]))
                rows.append((res["surface_name"], mname, qname, mae))

    if not rows:
        print("  No data for bar chart.")
        return

    surfaces = list(dict.fromkeys(r[0] for r in rows))
    methods = list(dict.fromkeys(r[1] for r in rows))
    n_surfaces = len(surfaces)
    n_methods = len(methods)
    n_quantities = len(QUANTITIES)

    # One group of bars per (surface, quantity); bars within group = methods
    n_groups = n_surfaces * n_quantities
    group_labels = [f"{s}\n{q}" for s in surfaces for q in QUANTITIES]

    x = np.arange(n_groups)
    bar_width = 0.8 / n_methods

    fig, ax = plt.subplots(figsize=(max(8, 2 * n_groups), 5))
    for j, method in enumerate(methods):
        vals = []
        for s in surfaces:
            for q in QUANTITIES:
                match = [r[3] for r in rows
                         if r[0] == s and r[1] == method and r[2] == q]
                vals.append(match[0] if match else 0.0)
        ax.bar(x + j * bar_width, vals, bar_width, label=method)

    ax.set_xticks(x + bar_width * (n_methods - 1) / 2)
    ax.set_xticklabels(group_labels)
    ax.set_ylabel("median |error|")
    ax.set_title("Curvature estimation error (all surfaces / methods / quantities)")
    ax.legend()
    ax.set_yscale("log")
    ax.grid(True, axis="y", alpha=0.3)

    plt.tight_layout()
    fname = "curvature_error_bar_chart.pdf"
    fig.savefig(fname, bbox_inches="tight")
    print(f"  Saved {fname}")
    plt.show()


# =====================================================================
# Summary table
# =====================================================================

def _print_summary_table(gt, methods):
    """Print a LaTeX-ready table of median absolute errors and correlations."""
    estimation_methods = [m for m in methods if m != "ground truth"]

    print("\n  %-10s" % "", end="")
    for qname in QUANTITIES:
        print(f"  {'MAE ' + qname:>12s}  {'corr ' + qname:>12s}", end="")
    print()

    for mname in estimation_methods:
        print(f"  {mname:10s}", end="")
        for qname in QUANTITIES:
            gt_v = gt[qname]
            est_v = methods[mname][qname]
            mask = np.isfinite(gt_v) & np.isfinite(est_v)
            if mask.sum() < 3:
                print(f"  {'---':>12s}  {'---':>12s}", end="")
                continue
            mae = np.median(np.abs(gt_v[mask] - est_v[mask]))
            r = np.corrcoef(gt_v[mask], est_v[mask])[0, 1]
            print(f"  {mae:12.6f}  {r:12.6f}", end="")
        print()

    # LaTeX table
    print("\n  % LaTeX table (paste into paper):")
    print(r"  \begin{tabular}{lccc}")
    print(r"    \toprule")
    print(r"    Method & $K$ & $H^2$ & $\|h\|$ \\")
    print(r"    \midrule")
    for mname in estimation_methods:
        row = f"    {mname}"
        for qname in QUANTITIES:
            gt_v = gt[qname]
            est_v = methods[mname][qname]
            mask = np.isfinite(gt_v) & np.isfinite(est_v)
            if mask.sum() < 3:
                row += " & ---"
                continue
            mae = np.median(np.abs(gt_v[mask] - est_v[mask]))
            row += f" & {mae:.2e}"
        row += r" \\"
        print(row)
    print(r"    \bottomrule")
    print(r"  \end{tabular}")


# =====================================================================
# Core runner
# =====================================================================

def run(
    surface_name: str,
    *,
    k_bu: int = 20,
    n_max: int | None = None,
    y_offset: float = 0.0,
):
    cfg = SURFACES[surface_name]

    print(f"\n=== {surface_name} ===")
    pts, normals, u_p, v_p = _load_pointcloud(surface_name)
    n_total = len(pts)

    if n_max is not None and n_total > n_max:
        rng = np.random.default_rng(42)
        idx = rng.choice(n_total, n_max, replace=False)
        pts, normals, u_p, v_p = pts[idx], normals[idx], u_p[idx], v_p[idx]
        print(f"  {len(pts)} points (downsampled from {n_total})")
    else:
        print(f"  {len(pts)} points")

    # Ground truth
    print("  Computing analytic curvature ...")
    K_gt, H2_gt, total_gt = cfg["analytic"](u_p, v_p)

    # Mask singular region where analytic curvature diverges
    if cfg["singular_mask_fn"] is not None:
        singular = cfg["singular_mask_fn"](u_p, v_p)
        K_gt[singular] = np.nan
        H2_gt[singular] = np.nan
        total_gt[singular] = np.nan

    gt = {"K": K_gt, "H2": H2_gt, "total": total_gt}

    # Blow-up
    print("  Computing blow-up curvature ...")
    bu = _blowup_curvature(pts, normals, k=k_bu)

    # Build methods dict in display order: ground truth -> jet -> cnc -> blow-up
    methods: dict[str, dict[str, np.ndarray]] = {"ground truth": gt}

    # Jet fitting baseline (pre-computed, from jet/ folder)
    jf = _load_jet_curvature(surface_name)
    if jf is not None:
        print(f"  Loading jet-fitting curvatures from jet/ ...")
        methods["jet"] = jf

    # CNC baseline (if file exists)
    cnc_path = Path(__file__).parent / "cnc" / f"cnc_{surface_name}.txt"
    if cnc_path.exists():
        print(f"  Loading CNC curvatures from {cnc_path} ...")
        cnc_data = np.loadtxt(cnc_path)
        K_cnc = cnc_data[:, 0]
        H_cnc = cnc_data[:, 1]
        H2_cnc = H_cnc ** 2
        total_cnc = np.sqrt(np.maximum(4.0 * H2_cnc - 2.0 * K_cnc, 0.0))
        methods["cnc"] = {"K": K_cnc, "H2": H2_cnc, "total": total_cnc}

    methods["blow-up"] = bu

    # Singularity distance
    print("  Computing singularity distance ...")
    sing_dist = cfg["singularity_distance"](u_p, v_p, pts)

    # Print correlations
    estimation_methods = [m for m in methods if m != "ground truth"]
    for qname in QUANTITIES:
        gt_v = gt[qname]
        for mname in estimation_methods:
            est_v = methods[mname][qname]
            mask = np.isfinite(gt_v) & np.isfinite(est_v)
            if mask.sum() > 3:
                r = np.corrcoef(gt_v[mask], est_v[mask])[0, 1]
                rmse = np.sqrt(np.mean((gt_v[mask] - est_v[mask]) ** 2))
                print(f"    {qname:>3s} {mname:>8s}: corr={r:.4f}  RMSE={rmse:.4f}")

    _print_summary_table(gt, methods)

    # -- Compute error fields --
    for mname in estimation_methods:
        for qname in QUANTITIES:
            methods[mname][qname + "_err"] = np.abs(
                methods[mname][qname] - gt[qname])
    for qname in QUANTITIES:
        gt[qname + "_err"] = np.zeros_like(gt[qname])

    # -- Polyscope panels --
    method_names = list(methods.keys())
    bbox = pts.max(axis=0) - pts.min(axis=0)
    spacing = bbox[0] * 1.4

    # Shared colour ranges
    shared_range: dict[str, tuple[float, float]] = {}
    for qname in ALL_QUANTITIES:
        all_v = [methods[m][qname] for m in method_names if qname in methods[m]]
        if all_v:
            if qname in _POSITIVE_QUANTITIES:
                _, vmin, vmax = _clamp_positive(np.concatenate(all_v))
            else:
                _, vmin, vmax = _clamp(np.concatenate(all_v))
            shared_range[qname] = (vmin, vmax)
        else:
            shared_range[qname] = (-1.0, 1.0)

    panel_names: list[str] = []
    panel_data: dict[str, dict[tuple, tuple]] = {}
    for i, method in enumerate(method_names):
        offset = np.array([i * spacing, y_offset, 0.0])
        pname = f"{surface_name}/{method}"
        cloud = ps.register_point_cloud(pname, pts + offset, radius=0.001)
        cloud.set_color((0.75, 0.75, 0.75))
        cloud.add_vector_quantity("normals", normals, enabled=False,
                                 color=(0.2, 0.2, 0.8))
        panel_names.append(pname)
        panel_data[pname] = {}

        for qname in ALL_QUANTITIES:
            if qname not in methods[method]:
                continue
            raw = np.nan_to_num(methods[method][qname], nan=0.0)

            sv_min, sv_max = shared_range[qname]
            panel_data[pname][(qname, False)] = (
                np.clip(raw, sv_min, sv_max), sv_min, sv_max)

            if qname in _POSITIVE_QUANTITIES:
                _, pv_min, pv_max = _clamp_positive(methods[method][qname])
            else:
                _, pv_min, pv_max = _clamp(methods[method][qname])
            panel_data[pname][(qname, True)] = (
                np.clip(raw, pv_min, pv_max), pv_min, pv_max)

    return dict(
        method_names=method_names,
        panel_names=panel_names,
        panel_data=panel_data,
        pts=pts,
        normals=normals,
        gt=gt,
        methods=methods,
        sing_dist=sing_dist,
        singularity_label=cfg["singularity_label"],
        surface_name=surface_name,
    )


# =====================================================================
# Main
# =====================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Curvature estimation vs analytic ground truth"
    )
    parser.add_argument(
        "-s", "--surface", type=str, default=None,
        choices=list(SURFACES.keys()),
        help="Surface to visualise (default: both)",
    )
    parser.add_argument("--k-bu", type=int, default=20, help="k-NN for blow-up")
    parser.add_argument("--n-max", type=int, default=None,
                        help="Downsample to at most this many points")
    args = parser.parse_args()

    surface_names = [args.surface] if args.surface else list(SURFACES.keys())

    ps.init()
    ps.set_ground_plane_mode("shadow_only")

    all_panel_names: list[str] = []
    all_panel_data: dict[str, dict] = {}
    all_results: list[dict] = []

    for idx, sname in enumerate(surface_names):
        result = run(sname, k_bu=args.k_bu,
                     n_max=args.n_max,
                     y_offset=idx * 8.0)
        all_panel_names.extend(result["panel_names"])
        all_panel_data.update(result["panel_data"])
        all_results.append(result)

    # Initialise vmin/vmax from the first quantity's shared range
    _init_key = ("K", False)
    _init_vmin = _init_vmax = 0.0
    for _pn in all_panel_names:
        if _init_key in all_panel_data[_pn]:
            _, _init_vmin, _init_vmax = all_panel_data[_pn][_init_key]
            break

    state = {
        "quantity": 0, "normalize": False, "normals": False,
        "vmin": _init_vmin, "vmax": _init_vmax,
    }

    _show_quantity("K", all_panel_names, all_panel_data, normalize=False,
                   vmin_override=state["vmin"], vmax_override=state["vmax"])

    def _refresh():
        _show_quantity(ALL_QUANTITIES[state["quantity"]], all_panel_names,
                       all_panel_data, normalize=state["normalize"],
                       vmin_override=state["vmin"],
                       vmax_override=state["vmax"])

    def callback():
        psim.TextUnformatted(
            f"Surfaces: {', '.join(surface_names)}  |  "
            f"Methods: {' | '.join(all_results[0]['method_names'])}"
        )
        psim.Separator()

        changed_q, new_q = psim.Combo("Quantity", state["quantity"],
                                      ALL_QUANTITIES)
        if changed_q:
            state["quantity"] = new_q
            # Reset vmin/vmax to defaults for the new quantity
            qname = ALL_QUANTITIES[new_q]
            key = (qname, state["normalize"])
            for _pn in all_panel_names:
                if key in all_panel_data[_pn]:
                    _, state["vmin"], state["vmax"] = all_panel_data[_pn][key]
                    break
            _refresh()

        changed_n, new_n = psim.Checkbox("Normalize per method",
                                         state["normalize"])
        if changed_n:
            state["normalize"] = new_n
            qname = ALL_QUANTITIES[state["quantity"]]
            key = (qname, new_n)
            for _pn in all_panel_names:
                if key in all_panel_data[_pn]:
                    _, state["vmin"], state["vmax"] = all_panel_data[_pn][key]
                    break
            _refresh()

        changed_vmin, new_vmin = psim.InputFloat("vmin", state["vmin"])
        changed_vmax, new_vmax = psim.InputFloat("vmax", state["vmax"])
        if changed_vmin or changed_vmax:
            state["vmin"] = new_vmin
            state["vmax"] = new_vmax
            _refresh()

        changed_nrm, new_nrm = psim.Checkbox("Show normals", state["normals"])
        if changed_nrm:
            state["normals"] = new_nrm
            for res in all_results:
                for pname in res["panel_names"]:
                    ps.get_point_cloud(pname).add_vector_quantity(
                        "normals", res["normals"], enabled=new_nrm,
                        color=(0.2, 0.2, 0.8))

        psim.Separator()

        for res in all_results:
            label = f"Error vs singularity ({res['surface_name']})"
            if psim.Button(label):
                _plot_error_vs_distance(
                    res["sing_dist"], res["gt"], res["methods"],
                    res["surface_name"], res["singularity_label"],
                )

        if psim.Button("Error bar chart (all surfaces)"):
            _plot_error_bar_chart(all_results)

        psim.Separator()

        for res in all_results:
            sn = res["surface_name"]
            if psim.Button(f"Export PLY ({sn})"):
                _export_ply(sn, res["pts"], res["normals"],
                            res["panel_names"], all_panel_data, state)
            if psim.Button(f"Export colour bar ({sn})"):
                _export_colourbar(sn, res["panel_names"], all_panel_data, state)

        if psim.Button("Export data (.npz)"):
            _export_data(all_results)

        if psim.Button("Screenshot"):
            fname = "curvature_analytic.png"
            ps.screenshot(fname, transparent_bg=False)
            print(f"Saved {fname}")

    ps.set_user_callback(callback)
    ps.show()


if __name__ == "__main__":
    main()
